PImage and_gate_image;
PImage nand_gate_image;
PImage not_gate_image;
PImage or_gate_image;
PImage nor_gate_image;
PImage xor_gate_image;
PImage xnor_gate_image;
PImage input_button_image;
PImage input_clock_image;
PImage input_image;
PImage output_image;
PImage input_image_true;
PImage output_image_true;
PImage connector_image;
PImage seven_seg_display_image;
PImage seven_seg_display_image_a;
PImage seven_seg_display_image_b;
PImage seven_seg_display_image_c;
PImage seven_seg_display_image_d;
PImage seven_seg_display_image_e;
PImage seven_seg_display_image_f;
PImage seven_seg_display_image_g;
PImage seven_seg_display_image_dp;

void loadImages(){
  and_gate_image = loadImage("Data/Textures/gates/and.png");
  nand_gate_image = loadImage("Data/Textures/gates/nand.png");
  not_gate_image = loadImage("Data/Textures/gates/not.png");
  or_gate_image = loadImage("Data/Textures/gates/or.png");
  nor_gate_image = loadImage("Data/Textures/gates/nor.png");
  xor_gate_image = loadImage("Data/Textures/gates/xor.png");
  xnor_gate_image = loadImage("Data/Textures/gates/xnor.png");
  input_button_image = loadImage("Data/Textures/interface/button.png");
  input_clock_image = loadImage("Data/Textures/interface/clock.png");
  input_image = loadImage("Data/Textures/interface/input_false.png");
  output_image = loadImage("Data/Textures/interface/output_false.png");
  input_image_true = loadImage("Data/Textures/interface/input_true.png");
  output_image_true = loadImage("Data/Textures/interface/output_true.png");
  connector_image = loadImage("Data/Textures/gates/connector.png");
  seven_seg_display_image = loadImage("Data/Textures/interface/7Segment/off.png");
  seven_seg_display_image_a = loadImage("Data/Textures/interface/7Segment/a.png");
  seven_seg_display_image_b = loadImage("Data/Textures/interface/7Segment/b.png");
  seven_seg_display_image_c = loadImage("Data/Textures/interface/7Segment/c.png");
  seven_seg_display_image_d = loadImage("Data/Textures/interface/7Segment/d.png");
  seven_seg_display_image_e = loadImage("Data/Textures/interface/7Segment/e.png");
  seven_seg_display_image_f = loadImage("Data/Textures/interface/7Segment/f.png");
  seven_seg_display_image_g = loadImage("Data/Textures/interface/7Segment/g.png");
  seven_seg_display_image_dp = loadImage("Data/Textures/interface/7Segment/dp.png");
}
